name = "youtube-downloader-cf"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
pages_build_output_dir = ".next"

[build.upload]
format = "service-worker"

[env.production]
vars = { YOUTUBE_API_KEY = "" } 